### ISSUE TITLE
Inserting a Business Process with "None" display makes ETL load errors

### ISSUE THREAD

**Issue by rverchere** [EyesOfNetworkCommunity/eyesofreport#28]
When creating a Business Process with EON, you can choose a display level to "None".
Then, this BP is synchronized with EOR, and makes EOR unable to process load data.

The ETL tries to insert in the table "d_application" a "none" value in the "DAP_PRIORITY" field, which is incorrect.

To avoid that:
- we could forbid the "none" value in Nagios Business Process.
- we could skip the "none" BP when inserting in base

**Comment by rverchere** [comment]
Here is the error:

```
2019/07/09 14:16:59 - Insertion_chargement.0 - Fin exécution étape (Entrées=0, Sorties=1, Lues=1, Ecrites=1, Maj=0, Erreurs=0)
2019/07/09 14:16:59 - Insert_Update_Application.0 - ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : Erreur inattendue
2019/07/09 14:16:59 - Insert_Update_Application.0 - ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : org.pentaho.di.core.exception.KettleStepException: 
2019/07/09 14:16:59 - Insert_Update_Application.0 - PDI doit arrêté le traitement car il a rencontré une erreur:
2019/07/09 14:16:59 - Insert_Update_Application.0 - 
2019/07/09 14:16:59 - Insert_Update_Application.0 - Error inserting/updating row
2019/07/09 14:16:59 - Insert_Update_Application.0 - Data truncation: Incorrect integer value: 'none' for column 'DAP_PRIORITY' at row 1
2019/07/09 14:16:59 - Insert_Update_Application.0 - 
2019/07/09 14:16:59 - Insert_Update_Application.0 - 
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.trans.steps.insertupdate.InsertUpdate.processRow(InsertUpdate.java:313)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at java.lang.Thread.run(Thread.java:745)
2019/07/09 14:16:59 - Insert_Update_Application.0 - Caused by: org.pentaho.di.core.exception.KettleDatabaseException: 
2019/07/09 14:16:59 - Insert_Update_Application.0 - Error inserting/updating row
2019/07/09 14:16:59 - Insert_Update_Application.0 - Data truncation: Incorrect integer value: 'none' for column 'DAP_PRIORITY' at row 1
2019/07/09 14:16:59 - Insert_Update_Application.0 - 
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.core.database.Database.insertRow(Database.java:1280)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.core.database.Database.insertRow(Database.java:1204)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.core.database.Database.insertRow(Database.java:1192)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.core.database.Database.insertRow(Database.java:1180)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.trans.steps.insertupdate.InsertUpdate.lookupValues(InsertUpdate.java:114)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.trans.steps.insertupdate.InsertUpdate.processRow(InsertUpdate.java:299)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	... 2 more
2019/07/09 14:16:59 - Insert_Update_Application.0 - Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect integer value: 'none' for column 'DAP_PRIORITY' at row 1
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	at org.pentaho.di.core.database.Database.insertRow(Database.java:1247)
2019/07/09 14:16:59 - Insert_Update_Application.0 - 	... 7 more
```
